# Generated by Django 5.1.3 on 2024-12-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='espaciodeestudio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='espacios/'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
