# Generated by Django 5.1.3 on 2024-12-30 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacios', '0002_cliente_espaciodeestudio_imagen_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espacios.cliente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espacios.espaciodeestudio')),
            ],
        ),
    ]
